<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.4.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (Mage::helper('advancedreviews')->getSummaryBlockEnabled() && is_array($this->getSummaryBlock())): ?>
    <?php if (count($this->getSummaryBlock())): ?>
        <div class="row n-review-summary-container ">
            <?php $ratings = $this->getSummaryBlock1() ?>
            <?php if($ratings): ?>
                <div class="ratings advancedreviews-summary-block col-xs-12 col-sm-6 col-md-8 col-lg-8 n-review-average-rating">
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo $ratings; ?>%"></div>
                    </div>
                </div>
            <?php endif; ?>
            <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 n-review-count">
                    <?php if ($parametr['votes_qty'] > 0): ?>
                        <div class="advancedreviews-reviews-count"><?= $this->__('Total') ?>
                            : <?php echo $parametr['votes_qty'] ?> <?= $this->__('Reviews') ?></div>
                    <?php endif; ?>
					<?php echo $this->getChildHtml('advancedreviews_login') ?>
					<?php if (Mage::helper('advancedreviews')->checkVersion('1.4.0.0')) {  } ?>
					<p id="do-login">
						<span><?= $this->__('To adding review') ?></span>
						<a style="background: #39d9b9;color: white;" href="<?= Mage::getBaseUrl() ?>customer/account/login/" class="button"><?php echo $this->__('Do Login') ?></a>
					</p>
                </div>
            <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>