﻿<!doctype html>
<html>
<head>
    <title>آزمون مزاج شناسی</title>
    <meta name="keywords"آزمون مزاج شناسی، طب سنتی، مزاج گرم و خشک، مزاج گرم و تر، مزاج سرد و تر، مزاج سرد و خشک، اخلاط اربعه، صفرا، سودا، بلغم، دم، قانون ابن سینا " ></meta>
    <meta name="description"
          آزمون مزاج شناسی برای شناخت مزاج افراد، آزمون مزاج شناسی بر اساس قانون ابن سینا، آزمون مزاج شناسی در طب سنتی، تشخیص گرمی و سردی مزاج، تشخیص تری و خشکی مزاج، گیاهان دارویی مناسب مزاج گرم و خشک، گیاهان دارویی مناسب مزاج گرم و تر، گیاهان دارویی مناسب مزاج سرد و خشک، گیاهان دارویی مناسب مزاج سرد و تر
    " ></meta>
    <meta http-equiv="Content-Type" content="test_text/html;charset=UTF-8">
    <link type="test_text/css" rel="stylesheet" href="css/mixed.css"></link>
    <meta name='viewport' content='width=device-width, user-scalable=no,initial-scale=1, maximum-scale=1, minimum-scale=1'/>
	<meta name="robots" content="index, follow">
</head>
<body>
	<div itemscope itemtype="http://schema.org/SoftwareApplication" id="test">
	<div id="m-content-main">
		<div class="test-banner"></div>
		<div id="phase1">
			<div id="explaination">
				<p>بذارید بیشتر باهم آشنا بشیم</p>
				<form action="" method="post" id="test-form">
					<div><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /></div>
					<div class="test-general-info">
						<div class="test-cust-name">
							<label for="qname"><span><span>نام</span></span></label>
							<input id="qname" type="text" name="qname">
						</div>
						<div class="test-cust-family">
							<label for="qfamily"><span><span>نام خانوادگی</span></span></label>
							<input id="qfamily" type="text" name="qfamily">
						</div>
						<div class="test-cust-gender">
							<label for="qage"><span><span>جنسیت</span></span></label>
							<select id="qage">
								<option value="volvo">زن</option>
								<option value="saab">مرد</option>
							</select>
						</div>
						<div class="test-cust-gender">
							<label for="qgender"><span><span>جنسیت</span></span></label>
							<select id="qgender">
								<option value="volvo">زن</option>
								<option value="saab">مرد</option>
							</select>
						</div>
						<div class="test-cust-email">
							<label for="qemail"><span><span>مرد</span></span></label>
							<input id="qemail" type="text" name="qemail">
						</div>
					</div>
				</form>
			</div>
			<div><h1>"لطفا به سوزیر به صورت صحیح و با دقت پاسخ دهید"</h1></div>
			<div id="questions">
				<div id="q1">
					<div id="test_text">
					   1. صبح ها وقتی از خواب بیدار می شوید رو پوستتان چه حسی دارد؟
					</div>
					<input id="q11" type="radio" name="s" value="1">
					<label for="q11"><span><span>مرد</span></span></label>
					<input id="q12" type="radio" name="s" value="2">
					<label for="q12"><span><span></span></span></label>
					<input id="q13" type="radio" name="s" value="3">
					<label for="q13"><span><span>مرد</span></span></label>
					<input id="q14" type="radio" name="s" value="4">
					<label for="q14"><span><span></span></span></label>
				</div>
				<div id="q2">
					<div id="test_text">
						2.لطفا سن خود را تعیین نمایید.
					</div>
					<input id="q21"   type="radio"  name="a" value="1">
					<label for="q21"><span><span></span></span></label>
					<input id="q22"   type="radio"  name="a" value="2">
					<label for="q22"><span><span></span></span></label>
					<input id="q23"   type="radio"  name="a" value="3">
					<label for="q23"><span><span></span></span></label>
					<input id="q24"   type="radio"  name="a" value="4">
					<label for="q24"><span><span></span></span></label>
				</div>
				<div id="q3">
					<div id="test_text">
						3.لطفا محل زندگی خود را از نظر آب و هوا تعیین نمایید.
					</div>
					<input id="q31"   type="radio"  name="w" value="1">
					<label for="q31"><span><span></span></span></label>
					<input id="q32"   type="radio"  name="w" value="2">
					<label for="q32"><span><span></span></span></label>
					<input id="q33"   type="radio"  name="w" value="3">
					<label for="q33"><span><span></span></span></label>
					<input id="q34"   type="radio"  name="w" value="4">
					<label for="q34"><span><span></span></span></label>
				</div>
			<div id="q4">
				<div id="test_text">
					4.پوست خشکی دارید یا پوستتان نرم است؟
				</div>
				<input id="q41"   type="radio"  name="d" value="1">
				<label for="q41"><span><span></span></span></label>
				<input id="q42"   type="radio"  name="d" value="2">
				<label for="q42"><span><span></span></span></label>
				<input id="q43"   type="radio"  name="d" value="3">
				<label for="q43"><span><span></span></span></label>
				<input id="q44"   type="radio"  name="d" value="4">
				<label for="q44"><span><span></span></span></label>
			</div>
			<div id="q5">
				<div id="test_text">

				</div>
				<input id="q51"   type="radio"  name="f" value="1">
				<label for="q51"><span><span></span></span></label>
				<input id="q52"   type="radio"  name="f" value="2">
				<label for="q52"><span><span></span></span></label>
				<input id="q53"   type="radio"  name="f" value="3">
				<label for="q53"><span><span></span></span></label>
				<input id="q54"   type="radio"  name="f" value="4">
				<label for="q54"><span><span></span></span></label>
			</div>
			<div id="q6">
				<div id="test_text">
					6.آیا عضلات پشت بازو و ساق پا و ران هایتان گوشتی و سفت است یا لاغر و شل؟
				</div>
				<input id="q61"   type="radio"  name="r" value="1">
				<label for="q61"><span><span></span></span></label>
				<input id="q62"   type="radio"  name="r" value="2">
				<label for="q62"><span><span></span></span></label>
				<input id="q63"   type="radio"  name="r" value="3">
				<label for="q63"><span><span></span></span></label>
				<input id="q64"   type="radio"  name="r" value="4">
				<label for="q64"><span><span></span></span></label>
			</div>
			<div id="q7">
				<div id="test_text">
					7.استخوان بندی درشتی دارید یا ریز اندام هستید؟
				</div>
				<input id="q71"   type="radio"  name="bo" value="1">
				<label for="q71"><span><span></span></span></label>
				<input id="q72"   type="radio"  name="bo" value="2">
				<label for="q72"><span><span></span></span></label>
				<input id="q73"   type="radio"  name="bo" value="3">
				<label for="q73"><span><span></span></span></label>
				<input id="q74"   type="radio"  name="bo" value="4">
				<label for="q74"><span><span></span></span></label>
			</div>
			<div id="q8">
				<div id="test_text">
					8.موهایتان صاف و لخت است یا مجعد و فر؟
				</div>
				<input id="q81"   type="radio"  name="ha" value="1">
				<label for="q81"><span><span></span></span></label>
				<input id="q82"   type="radio"  name="ha" value="2">
				<label for="q82"><span><span></span></span></label>
				<input id="q83"   type="radio"  name="ha" value="3">
				<label for="q83"><span><span></span></span></label>
				<input id="q84"   type="radio"  name="ha" value="4">
				<label for="q84"><span><span></span></span></label>
			</div>
		</div>
		<div id="result">
			<div id="image" style="display: none">
				<div id="image1" style="display: none"></div>
				<div id="image2" style="display: none"></div>
				<div id="image3" style="display: none"></div>
			</div>
			<div id="general">
				<div id="genertitle" style="height: 50px !important;">
					مزاج شما و راه های حفظ مزاجتان
				</div>
				<div id="genercontent">
				</div>
			</div>
			<div id="substance">
				<div id="subtitle">
					شما غلبه اخلاط زیر را دارید و می توانید برای تعدیل این اخلاط از راهکارهای زیر استفاده نمایید.
				</div>
				<div id="subcontent">
				</div>
			</div>
			<div id="gender">
				<div id="gentitle" style="height: 50px!important;">
					مزاج جنس شما و توصیه های گیاهی برای اعتدال این مزاج
				</div>
				<div id="gencontent">
				</div>

			</div>
			<div id="age">
				<div id="agetitle"  style="height: 50px!important;">
					مزاج سن شما و توصیه های گیاهی برای اعتدال این مزاج
				</div>
				<div id="agecontent">
				</div>
			</div>
		</div>
	</body>
</html>