<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.4.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if (Mage::helper('advancedreviews')->getSummaryBlockEnabled() && is_array($this->getSummaryBlock())): ?>
    <?php if (count($this->getSummaryBlock())): ?>
        <div class="row n-review-summary-container ">
            <?php $ratings = $this->getSummaryBlock1() ?>
            <?php if($ratings): ?>
                <div class="ratings advancedreviews-summary-block col-xs-12 col-sm-6 col-md-6 col-lg-6 n-review-average-rating n-review-summary-block">
                    <strong style="margin-bottom: 20px;"><?= $this->__('Average rating for this product is:') ?></strong>
                    <div class="n-review-rating-box">
                        <div class="n-review-rating" style="width:<?php echo $ratings; ?>%"></div>
                    </div>
                </div>
            <?php endif; ?>
            <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 n-review-count">
                    <?php if ($parametr['votes_qty'] > 0): ?>
                        <div class="advancedreviews-reviews-count"><?= $this->__('Total') ?>
                            : <?php echo $parametr['votes_qty'] ?> <?= $this->__('Reviews') ?></div>
                    <?php endif; ?>
					<?php echo $this->getChildHtml('advancedreviews_login') ?>
					<?php if (Mage::helper('advancedreviews')->checkVersion('1.4.0.0')) {  } ?>
					<p id="do-login" class="n-review-summary-block">
                        <strong><?= $this->__('Have you purchased this product?') ?></strong>
						<span><?= $this->__('To adding review') ;?></span>
						<a style="background: #52c3c6;color: black;border: none;" id="popuploginbutton" class="button"><?php echo $this->__('Do Login') ?></a>
					</p>
					<div id="nar-login-form" class="n-review-float-form" style="display: none">
                        <div class="col-xs-12 col-sm-6 col-md-5 col-lg-4" style=" margin: 0 auto; height: 70%; display: table;top: 15%;">
                            <button id="popuploginbutton-exit" style="position: absolute; right: 10px; top: 0;">✕</button>
                            <?php echo $this->getChildHtml('advancedreviews_popuplogin') ?>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 n-review-count">
                    <?php if ($parametr['votes_qty'] > 0): ?>
                        <div class="advancedreviews-reviews-count"><?= $this->__('Total') ?>
                            : <?php echo $parametr['votes_qty'] ?> <?= $this->__('Reviews') ?></div>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('advancedreviews_login') ?>
                    <?php if (Mage::helper('advancedreviews')->checkVersion('1.4.0.0')) {  } ?>
                    <div id="do-login" class="n-review-summary-block" style="color: #000;">
                        <strong><?= $this->__('Have you purchased this product?') ?></strong>
                        <span style="padding: 0; margin-bottom: 10px;"><?= $this->__('You can share your review.') ?></span>
                        <button class="button nar-button-green" id="nar-review-btn"><?php echo $this->__('Give your review') ?></button>
                    <div id="nar-review-form" class="n-review-float-form" style="display: none">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6" style="margin: 0 auto">
                            <button id="nar-exit">✕</button>
                            <?php echo $this->getChildHtml('review_form') ?>
                        </div>
                    </div>
                    </div>
                </div>
            <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<script>
    jQuery( document ).ready(function() {
        jQuery('#nar-review-btn').on('click', function() { jQuery("#nar-review-form").show(); });
        jQuery('#nar-exit').on('click', function() { jQuery("#nar-review-form").hide(); });
		jQuery('#popuploginbutton').on('click', function() { jQuery("#nar-login-form").show(); });
        jQuery('#popuploginbutton-exit').on('click', function() { jQuery("#nar-login-form").hide(); });
		
    });
</script>
