<?php
/**
 * ┌┬┐┬ ┬┌─┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌─┐┌─┐ ┌─┐┌─┐┌┬┐
 *  │ └┬┘├─┘│ │└─┐ │ │ │├┬┘├┤ └─┐ │  │ ││││
 *  ┴  ┴ ┴  └─┘└─┘ ┴ └─┘┴└─└─┘└─┘o└─┘└─┘┴ ┴
 *
 * @copyright    Copyright (C) 2015 typostores.com. All Rights Reserved.
 *
 */
?>
<?php
$theme = $this->helper('typologancee');
$helpImg = $this->helper('typologancee/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if($theme->getCfg('category/aspect_ratio')){
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper            = $this->helper('catalog/output');
/* @var $this TypoStores_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$pricePrefixId      = $this->getData('price-prefix');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
$lazy               = $carousel == 1 ? 'owl-lazy' : 'lazy';
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');

$column_count       = $this->getData('column_count');
$column_count_1600  = $this->getData('column_count_1600');
$column_count_1200  = $this->getData('column_count_1200');
$column_count_992   = $this->getData('column_count_992');
$column_count_768   = $this->getData('column_count_768');

if ($column_count_1600) {
    $grid_block = $this->helper('typowidget')->gridBlockWidget($column_count, $column_count_1600, $column_count_1200, $column_count_992, $column_count_768);
}
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel owl-theme">
        <?php endif ?>
        <?php if ($i == 0 || ($row > 1 && $i % $row == 0)): ?>
        <div class="category-products collection-position03">
        <ul class="products-grid <?php if ($carousel == 0) echo 'row' ?> <?php echo $carousel && $row == 1 ? 'owl-carousel owl-theme' : '' ?>">
    <?php endif ?>
        <?php $i++ ?>
        <li class="item <?php if ($carousel == 0) echo $grid_block; ?>">
            <div class="item-inner">
                <div class="product-item">
                    <div class="content products-list">
                        <div class="product-show">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <span class="front margin-image">
                                    <img class="img-responsive <?php echo $lazy ?> <?php echo $hoveraltClass;?>" data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" src="<?php echo $this->getSkinUrl('images/blank.png', $theme->checkSSL()) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $imgWidth ?>" height="<?php echo $imgHeight ?>" />
                                </span>
                                <?php if ($theme->getCfg('category/alt_image')): ?>
                                    <span class="product-img-additional back margin-image">
										 <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
									</span>
                                <?php endif; ?>
                                <div class="product-date" data-date="<?php echo Mage::helper('typowidget')->getDate($_product) ?>"></div>
                            </a>
                        </div>
                    </div>

                    <div class="top-actions-inner">
                        <h3 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h3>
                        <div class="table">
                            <?php echo $this->getPriceHtml($_product, true, '-'.$pricePrefixId) ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        </li>
        <?php if ($i == $count || $i == 0 || ($row > 1 && $i % $row == 0)): ?>
        </ul>
        </div>
    <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
